name: Dev Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  
  build:
      strategy:
         matrix:
            os: [windows-latest, macos-latest, macos-12, ubuntu-20.04]

      runs-on: {{ matrix.os }}

      steps:
        - uses: actions/checkout@v3
        - name: compile
          run: g++ -o tinyencrypt_dev.exe main.cpp
